services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: watermill
      POSTGRES_DB: watermill
      POSTGRES_PASSWORD: "password"
